sudo: required
services:
  - docker

before_install:
  - docker build -t rijkl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t rijukl/multi-client ./client
  - docker build -t rijukl/multi-nginx ./nginx
  - docker build -t rijukl/multi-server ./server
  - docker build -t rijukl/multi-worker ./worker
  - echo "$DOCKER_PASSWORD: | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rijukl/multi-client
  - docker push rijukl/multi-nginx
  - docker push rijukl/multi-server
  - docker push rijukl/multi-worker
